config/routes.rb
Rails.application.routes.draw do

    # admin

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: { # skip オプションを使用し不要なルーティングを削除
    :sessions => 'admin/sessions',
    :registrations => 'admin/registrations',
  }

  namespace :admin do
  	get '/search'=>'search#search'
    resources :customers,only: [:index,:show,:edit,:update] do
      get 'history', on: :member
    end
  	resources :items,only: [:index,:new,:create,:show,:edit,:update,]
  	resources :genres,only: [:index,:create,:edit,:update, :show]
  	resources :orders,only: [:index,:show,:update] do
  	  member do
  	   # get 'history' => 'admin/customers/history'
        get :current_index
        resource :order_details,only: [:update]
      end
      collection do
        get :today_order_index
      end
    end
  end

  # customer

devise_for :customers,skip: [:passwords], controllers: { # skip オプションを使用し不要なルーティングを削除
    :sessions => 'public/sessions',
    :registrations => 'public/registrations',
    :passwords => 'public/passwords'
  }

  get 'about' => 'public/homes#about'
  root 'public/homes#top'
  get '/customers/contact' => 'public/customers#contact'

  scope module: :public do
    resources :items,only: [:index, :show]
    resources :search,only: [:search]
  	get '/search'=>'search#search'
    # deviseと衝突してしまうので、オリジナルに変更
    get 'edit/customers' => 'customers#edit'
    patch 'update/customers' => 'customers#update'

  	resource :customers,only: [:edit,:update,:show] do
  		collection do
  	     get 'quit'
  	     patch 'out'
  	  end
  	end

      resources :cart_items,only: [:index,:update,:create,:destroy] do
        collection do
          delete '/' => 'cart_items#all_destroy'
        end
      end

      resources :orders,only: [:new,:index,:show,:create] do
        collection do
          post 'confirm'
          get 'thanks'
        end
      end

      resources :addresses,only: [:index,:create,:edit,:update,:destroy]
    end
  end

app/models/customer.rb
class Customer < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :kana_last_name, presence: true
  validates :kana_first_name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :email, uniqueness: true

  def self.search_for(content,method)
    return none if content.blank?
     if method == 'forward'
      # カラムが2つの部分を1つに補う
       f_customer = Customer.where('first_name LIKE ?',content + '%')
       l_customer = Customer.where('last_name LIKE ?',content + '%')

       customers = f_customer + l_customer
     elsif method == 'backword'
       Customer.where('first_name LIKE ?', '%' + content)
       f_customer = Customer.where('first_name LIKE ?', '%' + content)
       l_customer = Customer.where('last_name LIKE ?', '%' + content)

       customers = f_customer + l_customer
     else
       f_customer = Customer.where('first_name LIKE ?', '%' + content + '%')
       l_customer = Customer.where('last_name LIKE ?', '%' + content + '%')

       customers = f_customer + l_customer
     end
  end

  def full_name
    self.last_name + " " + self.first_name
  end

  def kana_full_name
    self.kana_last_name + " " + self.kana_first_name
  end

  def active_for_authentication?
    super && (self.is_deleted == false)
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
   before_action :authenticate_admin!

  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "会員情報を更新しました。"
      redirect_to admin_customer_path
    else
      render 'edit'
    end
  end

  def history
    @customer = Customer.find(params[:id])
    @orders = Order.page(params[:page]).per(10)
  end

  private
   def customer_params
     params.require(:customer).permit(
       :first_name,:last_name,:kana_first_name,:kana_last_name,:postal_code,:address,:phone_number,:email,:is_deleted)
   end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/_index.html.erb
    <table class="table">
      <thead>
        <tr style="background-color: #EEEEEE;">
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
        </tr>
      </thead>

      <tbody>
        <% customers.each do |customer| %>
         <tr>
             <td class="info col-xs-1">
                <%= customer.id %>
             </td>
             <td class="text-left">

					  	<%= link_to customer.full_name, admin_customer_path(customer) %>

             </td>
             <td class="text-left">
                <%= customer.email %>
             </td>
             <td class="col-xs-2">
                <% if customer.is_deleted == true%>
                  <p class="text-secondary">退会済</p>
                <% else %>
                  <p class="text-success">有効</p>
                <% end %>
             </td>
         </tr>
        <% end %>
      </tbody>
    </table>

app/views/admin/customers/edit.html.erb
<div class="container">
  <h2 class="font-weight-bold my-5"><span style="background-color: #EEEEEE"> <%= @customer.full_name %>　さんの会員情報編集 </span></h2>

<div class="container">
    <div class="row">
      <div class="col-lg-7">

  <%= form_with model: @customer, url: admin_customer_path, local: true do |f| %>
    <div class="col-xs-10 offset-1">
      <div class="form-group col-xs-9">
        <%= f.label :"会員ID".upcase, class: "col-sm-4" %>
        <%= f.label :"#{@customer.id}" %>
      </div>
      <div class="form-group col-xs-9">
        <%= f.label :"氏名", class: "col-sm-4 control-label" %>
        <%= f.text_field :last_name, class: "col-sm-3 form-control-static" %>
        <%= f.text_field :first_name, class: "col-sm-3 form-control-static name" %>
      </div>

      <div class="form-group col-xs-9">
        <%= f.label :"フリガナ", class: "col-sm-4 control-label" %>
        <%= f.text_field :kana_last_name, class: "col-sm-3 form-control-static name" %>
        <%= f.text_field :kana_first_name, class: "col-sm-3 form-control-static name" %>
      </div>

      <div class="form-group col-xs-9">
        <%= f.label :"郵便番号", class: "col-sm-4 control-label" %>
        <%= f.text_field :postal_code, class: "col-sm-3" %>
      </div>

      <div class="form-group col-xs-9">
        <%= f.label :"住所", class: "col-sm-4 control-label" %>
        <%= f.text_field :address, class: "col-sm-7" %>
      </div>

      <div class="form-group col-xs-9">
        <%= f.label :"電話番号", class: "col-sm-4 control-label" %>
        <%= f.text_field :phone_number, class: "col-sm-4" %>
      </div>

      <div class="form-group col-xs-9">
        <%= f.label :"メールアドレス", class: "col-sm-4 control-label" %>
        <%= f.text_field :email, class: "col-sm-6" %>
      </div>

      <div class="form-group col-xs-9">
        <%= f.label :"会員ステータス", class: "col-sm-4 control-label" %>
        　<%= f.radio_button :is_deleted, false %>
        　<%= f.label :is_deleted, "有効"%>
        　<%= f.radio_button :is_deleted, true %>
        　<%= f.label :is_deleted, "退会" %>
      </div>
    </div>
      <div class="form-group col-xs-9 d-flex justify-content-around">
        <%= f.submit '変更を保存' ,class: "btn btn-success" %>
        <%= link_to '会員詳細画面へ戻る',admin_customer_path, class:"btn btn-outline-secondary"%>
      </div>

  <% end %>

  </div>
</div>

app/views/admin/customers/history.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
        <h2 class="font-weight-bold my-5"><span style="background-color: #EEEEEE"> <%= @customer.full_name %>　さんの注文履歴 </span></h2>

  <table class="table">
    <thead>
      <tr style="background-color: #EEEEEE;">
        <th>購入日時</th>
        <th>注文個数</th>
        <th>注文ステータス</th>
      </tr>
      <tbody>
        <% @orders.each do |order| %>
        <tr>
          <td>
            <%= link_to admin_order_path(order) do %>
              <%= order.created_at.strftime("%Y-%m-%d %H:%M:%S")%>
            <% end %>
          </td>

          <td><% order_details = OrderDetail.where(order_id: order.id) %>
		            <% count = 0 %>
            		<% order_details.each do |order_detail| %>
            				<% count += order_detail.amount %>
            		<% end %>
            		<%= count %></td>
          <td><%= order.status %></td>


        </tr>
        <% end %>
      </tbody>
    </thead>
  </table>
   <div class="d-flex justify-content-center"><%= paginate(@orders)%></div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
 <h2 class="font-weight-bold my-5"><span style="background-color: #EEEEEE"> 会員一覧 </span></h2>

  <div class="row d-flex justify-content-center">
  <%= render 'index', customers: @customers%>
 </div>
 <div class="d-flex justify-content-center"><%= paginate(@customers)%></div>
</div>

app/views/admin/customers/show.html.erb
<style>
  .table th {
    width: 30%;
  }

  .table td {
    width: 70%;
  }
</style>

  <h2 class="font-weight-bold my-5"><span style="background-color: #EEEEEE"> <%= @customer.full_name %>　さんの会員詳細 </span></h2>

<div class="container">
    <div class="row">
      <div class="col-lg-7">

<table class="table">
  <tr>
    <th class="text-center">会員ID</th>
    <td><%= @customer.id %></td>
  </tr>
  <tr>
    <th class="text-center">氏名</th>
    <td><%= @customer.full_name %></td>
  </tr>
  <tr>
    <th class="text-center">フリガナ</th>
    <td><%= @customer.kana_full_name %></td>
  </tr>
  <tr>
    <th class="text-center">郵便番号</th>
    <td>〒<%= @customer.postal_code %></td>
  </tr>
  <tr>
    <th class="text-center">住所</th>
    <td><%= @customer.address %></td>
  </tr>
  <tr>
    <th class="text-center">電話番号</th>
    <td><%= @customer.phone_number %></td>
  </tr>
  <tr>
    <th class="text-center">メールアドレス</th>
    <td><%= @customer.email %></td>
  </tr>
  <tr>
    <th class="text-center">会員ステータス</th>
    <% if @customer.is_deleted == true %>
      <td class="text-secondary">退会済み</td>
    <% else %>
      <td class="text-success">有効</td>
    <% end %>
  </tr>
</table>

          <div class="d-flex justify-content-around">
            <p><%= link_to "編集する",edit_admin_customer_path, class:"btn btn-success" %></p>
            <p><%= link_to "注文履歴一覧を見る",history_admin_customer_path, class:"btn btn-primary" %></p>
          </div>
   　　 </div>
  　</div>
 </div>