config/routes.rb
Rails.application.routes.draw do

    # admin

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: { # skip オプションを使用し不要なルーティングを削除
    :sessions => 'admin/sessions',
    :registrations => 'admin/registrations',
  }

  namespace :admin do
  	get '/search'=>'search#search'
    resources :customers,only: [:index,:show,:edit,:update] do
      get 'history', on: :member
    end
  	resources :items,only: [:index,:new,:create,:show,:edit,:update,]
  	resources :genres,only: [:index,:create,:edit,:update, :show]
  	resources :orders,only: [:index,:show,:update] do
  	  member do
  	   # get 'history' => 'admin/customers/history'
        get :current_index
        resource :order_details,only: [:update]
      end
      collection do
        get :today_order_index
      end
    end
  end

  # customer

devise_for :customers,skip: [:passwords], controllers: { # skip オプションを使用し不要なルーティングを削除
    :sessions => 'public/sessions',
    :registrations => 'public/registrations',
    :passwords => 'public/passwords'
  }

  get 'about' => 'public/homes#about'
  root 'public/homes#top'
  get '/customers/contact' => 'public/customers#contact'

  scope module: :public do
    resources :items,only: [:index, :show]
    resources :search,only: [:search]
  	get '/search'=>'search#search'
    # deviseと衝突してしまうので、オリジナルに変更
    get 'edit/customers' => 'customers#edit'
    patch 'update/customers' => 'customers#update'

  	resource :customers,only: [:edit,:update,:show] do
  		collection do
  	     get 'quit'
  	     patch 'out'
  	  end
  	end

      resources :cart_items,only: [:index,:update,:create,:destroy] do
        collection do
          delete '/' => 'cart_items#all_destroy'
        end
      end

      resources :orders,only: [:new,:index,:show,:create] do
        collection do
          post 'confirm'
          get 'thanks'
        end
      end

      resources :addresses,only: [:index,:create,:edit,:update,:destroy]
    end
  end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_details, dependent: :destroy
	belongs_to :customer

	validates :customer_id, :address, :name, :shipping_cost,
			  		:total_payment, :payment_method,
			  		presence: true
	validates :postal_code, length: {is: 7}, numericality: { only_integer: true }
	validates :shipping_cost, :total_payment, numericality: { only_integer: true }

	enum payment_method: {"クレジットカード": 0,"銀行振込": 1}
	enum status: {"入金待ち": 0,"入金確認": 1,"製作中": 2,"発送準備中": 3, "発送済み": 4}
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
   before_action :authenticate_admin!

  def index
    @orders = Order.page(params[:page]).per(10)
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    flash[:notice] = "注文ステータスを変更しました"
    redirect_to admin_order_path(@order)

    if @order.status == "入金確認"
      @order.order_details.each do |order_detail|
        order_detail.update(making_status: 1)
      end
    end
  end

  private

  def order_params
    params.require(:order).permit(:shipping_cost, :total_payment, :name, :payment_method, :address, :postal_code, :status, :making_status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<% provide(:title, "注文一覧") %>
<div class="container">
  <h2 class="my-5">注文履歴一覧</h2>
  <table class="table">
    <thead>
      <tr>
        <th>購入日時</th>
        <th>購入者</th>
        <th>注文個数</th>
        <th>注文ステータス</th>
      </tr>
      <tbody>
        <% @orders.each do |order| %>
        <tr>
          <td>
            <%= link_to admin_order_path(order) do %>
              <%= order.created_at.strftime("%Y-%m-%d %H:%M:%S")%>
            <% end %>
          </td>
          <td><%= order.customer.full_name %></td>


          <td><% order_details = OrderDetail.where(order_id: order.id) %>
		            <% count = 0 %>
            		<% order_details.each do |order_detail| %>
            				<% count += order_detail.amount %>
            		<% end %>
            		<%= count %></td>
          <td><%= order.status %></td>


        </tr>
        <% end %>
      </tbody>
    </thead>
  </table>
   <div class="d-flex justify-content-center"><%= paginate(@orders)%></div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <h2 class="font-weight-bold my-5"><span style="background-color: #EEEEEE"> 注文履歴詳細 </span></h2>

<div class="container">
    <div class="row">
      <div class="col-lg-7">

      <table class="table table-borderless">
         <thead>
            <tr><th>購入者</th><td>
              <%= link_to admin_customer_path(@order.customer.id) do %>
                <%= @order.customer.full_name %>
              <% end %></td></tr>
            <tr><th>注文日</th><td><%= @order.created_at.strftime("%Y-%m-%d %H:%M:%S")%></td></tr>
            <tr><th>配送先</th><td>〒<%= "#{@order.postal_code} #{@order.address} 　#{@order.name}" %></td></tr>
            <tr><th>支払方法</th><td><%= @order.payment_method %></td></tr>
            <tr>
             <th>注文ステータス</th>
              <td>
                <%= form_with(model: @order, url: admin_order_path, method: :patch, local: true) do |f| %>
                <%= f.select :status, Order.statuses.keys,class:"status"%>
                <%= f.submit '更新', class:"btn btn-sm btn-success" %>
                <% end %>
              </td>
           </tr>
         </thead>
     </table>
    </div>
  </div>

  <div class="row justify-content-between">
    <div class="col-lg-7">
      <table class="table table-borderless">
        <thead class="thead-light">
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>制作ステータス</th>
          </tr>
        </thead>

        <tbody>
          <% @order_details.each do |order_detail|%>
            <tr>
              <td><p><%= order_detail.item.name %></p></td>
              <td><p><%= order_detail.item.with_tax_price.to_s(:delimited) %></p></td>
              <td><p><%= order_detail.amount %></p></td>
              <td><p><%= (order_detail.item.with_tax_price * order_detail.amount).to_s(:delimited) %></p></td>
              <td>
                <%= form_with(model: order_detail, url: admin_order_details_path(order_detail.id), method: :patch, local: true) do |f|%>
                <%= f.select :making_status, OrderDetail.making_statuses.keys, class:"making_status"%>
                <%= f.submit "更新", class:"btn btn-success"%>
                <% end %>
              </td>
            </tr>
            <% end %>
        </tbody>
      </table>
      </div>

    <div class="col-lg-4">
      <div class="text-right"> <!-- 右側のテーブルを右寄せ -->
        <table class="table">
          <tr>
            <th>商品合計</th>
            <td class="text-right col-xs-5">¥<%= (@order.total_payment - @order.shipping_cost).to_s(:delimited) %></td>
          </tr>
          <tr>
            <th>送料</th>
            <td class="text-right col-xs-5">¥<%= @order.shipping_cost %></td>
          </tr>
          <tr>
            <th>請求金額</th>
            <td class="text-right col-xs-5">¥<%= @order.total_payment.to_s(:delimited) %></td>
          </tr>
          <tr>
            <th></th>
            <td class="text-right col-xs-5"><%= link_to "注文履歴へ戻る", admin_orders_path, class:"btn btn-outline-secondary"%></td>
          </tr>
      </table>
      </div>
    </div>
  </div>
</div>