config/routes.rb
Rails.application.routes.draw do

    # admin

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: { # skip オプションを使用し不要なルーティングを削除
    :sessions => 'admin/sessions',
    :registrations => 'admin/registrations',
  }

  namespace :admin do
  	get '/search'=>'search#search'
    resources :customers,only: [:index,:show,:edit,:update] do
      get 'history', on: :member
    end
  	resources :items,only: [:index,:new,:create,:show,:edit,:update,]
  	resources :genres,only: [:index,:create,:edit,:update, :show]
  	resources :orders,only: [:index,:show,:update] do
  	  member do
  	   # get 'history' => 'admin/customers/history'
        get :current_index
        resource :order_details,only: [:update]
      end
      collection do
        get :today_order_index
      end
    end
  end

  # customer

devise_for :customers,skip: [:passwords], controllers: { # skip オプションを使用し不要なルーティングを削除
    :sessions => 'public/sessions',
    :registrations => 'public/registrations',
    :passwords => 'public/passwords'
  }

  get 'about' => 'public/homes#about'
  root 'public/homes#top'
  get '/customers/contact' => 'public/customers#contact'

  scope module: :public do
    resources :items,only: [:index, :show]
    resources :search,only: [:search]
  	get '/search'=>'search#search'
    # deviseと衝突してしまうので、オリジナルに変更
    get 'edit/customers' => 'customers#edit'
    patch 'update/customers' => 'customers#update'

  	resource :customers,only: [:edit,:update,:show] do
  		collection do
  	     get 'quit'
  	     patch 'out'
  	  end
  	end

      resources :cart_items,only: [:index,:update,:create,:destroy] do
        collection do
          delete '/' => 'cart_items#all_destroy'
        end
      end

      resources :orders,only: [:new,:index,:show,:create] do
        collection do
          post 'confirm'
          get 'thanks'
        end
      end

      resources :addresses,only: [:index,:create,:edit,:update,:destroy]
    end
  end

app/views/layouts/_error_message.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" class="alert alert-primary" role="alert">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
       <p class="text-success"><%= flash[:notice] %></p>
<% end %>
<% if flash[:alert] %>
       <p class="text-danger"><%= flash[:alert] %></p>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p class="text-center" style="margin: 30px auto;">© 2023 06 YutaMorimoto</p>
  <div class="d-flex justify-content-center">
    <a href="#" class="mx-1 text-dark"><i class="fab fa-twitter fa-2x"></i></a>
    <a href="#" class="mx-5 text-dark"><i class="fab fa-instagram fa-2x"></i></a>
    <a href="#" class="mx-1 text-dark"><i class="far fa-envelope fa-2x"></i></a>
  </div>
</footer>

app/views/layouts/_header.html.erb
<head>
  <style>
    .custom-div {
      margin-bottom: 30px;
    }
  </style>
</head>

<header class="shadow-sm">
<div class="custom-div d-flex justify-content-center align-items-center">
  <div class="flex-fill">
      <% if admin_signed_in? %>
        <%= link_to admin_orders_path, class:"header-title navbar-brand" do %>
          <%= image_tag "logo.jpg", alt: "NaganoCAKE" %>
        <% end %>
      <% else %>
        <%= link_to root_path, class:"header-title navbar-brand" do %>
          <%= image_tag "logo.jpg", alt: "NaganoCAKE" %>
        <% end %>
      <% end %>
  </div>

  <nav class="nav navbar navbar-expand-lg justify-content-end">
      <button class="navbar-toggler mx-5" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div id="navbarNavDropdown">
        <% if customer_signed_in? %>
          <ul class="navbar-nav">
            <li class="nav-item active">
              <span class="nav-link text-dark">ようこそ <%= current_customer.last_name %> <%= current_customer.first_name %> さん</span>
            </li>
            <li class="nav-item">
              <%= link_to "マイページ", customers_path(current_customer), class: "btn btn-outline-secondary mx-3 my-1"%>
            </li>
            <li class="nav-item ">
              <%= link_to "商品一覧", items_path, class: 'btn btn-outline-secondary mx-3 my-1'%>
            </li>
            <li class="nav-item">
              <%= link_to "カート", cart_items_path, class: 'btn btn-outline-secondary mx-3 my-1'%>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'btn btn-outline-secondary mx-3 my-1'%>
            </li>
          </ul>
          <div class="nav-item pull-right">
            <%= render "layouts/search" %>
          </div>
        <% elsif admin_signed_in? %>
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "商品一覧", admin_items_path, class: 'btn btn-outline-secondary mx-3 my-1' %>
            </li>
            <li class="nav-item">
              <%= link_to "会員一覧", admin_customers_path, class:'btn btn-outline-secondary mx-3 my-1'%>
            </li>
            <li class="nav-item">
              <%= link_to "注文履歴一覧", admin_orders_path, class:'btn btn-outline-secondary mx-3 my-1'%>
            </li>
            <li class="nav-item">
              <%= link_to "ジャンル一覧", admin_genres_path, class: 'btn btn-outline-secondary mx-3 my-1'%>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト",destroy_admin_session_path, method: :delete,class: 'btn btn-outline-secondary mx-3 my-1'%>
            </li>
          </ul>
          <div class="nav-item pull-right">
            <%= render "layouts/search" %>
          </div>
        <% else %>
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "about", about_path, class: 'btn btn-outline-secondary mx-3 my-1' %>
            </li>
            <li class="nav-item">
              <%= link_to "商品一覧", items_path, class: 'btn btn-outline-secondary mx-3 my-1' %>
            </li>
            <li class="nav-item">
              <%= link_to "新規登録", new_customer_registration_path, class: 'btn btn-outline-secondary mx-3 my-1'%>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_customer_session_path, class: 'btn btn-outline-secondary mx-3 my-1'%>
            </li>
          </ul>
          <div class="nav-item pull-right">
            <%= render "layouts/search" %>
          </div>
        <% end %>

  </div>
</header>

app/views/layouts/_search.html.erb
<% if admin_signed_in? %>
  <%= form_with url: admin_search_path, method: :get, local: true do |f| %>
    <div class="row d-flex justify-content-end mt-2 mr-3">
      <div class="col-md-3 p-0">
        <%= f.text_field :content, placeholder: "Search", class: "form-control" %>
      </div>
      <div class="col-md-3 p-0">
        <%= f.select :model, options_for_select({"Customer" => "customer", "Item" => "item"}, selected: "customer"), {}, class: "form-control" %>
      </div>
      <div class="col-md-3 p-0">
        <%= f.select :method, options_for_select({"前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial"}, selected: "forward"), {}, class: "form-control" %>
      </div>
      <div class="col-md-2 p-0">
        <%= button_tag type: "submit", class: "btn btn-outline-secondary m-1" do %>
          <i class="fa-solid fa-magnifying-glass"></i>
        <% end %>
      </div>
    </div>
  <% end %>

<% else %>
  <%= form_with url: search_path, method: :get, local: true do |f| %>
    <div class="d-flex justify-content-end mt-2 mr-3" >
      <%= f.text_field :content, placeholder: "商品検索", class:"form-control" %>
      <%= f.select :method, options_for_select({"前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial"}, selected: "forward"), {}, class: "form-control form-select rounded-pill" %>
      <%= button_tag type: "submit", class:"btn btn-outline-secondary m1-2" do %>
        <i class="fa-solid fa-magnifying-glass"></i>
      <% end %>
    </div>
  <% end %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <script src="https://kit.fontawesome.com/6c57885749.js" crossorigin="anonymous"></script>
  <head>
  <title>ながのcake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrapper">

    <%= render "layouts/header"%>
    <main>

    <div class="container">
      <div id="flash">
        <%= render "layouts/flash" %>
      </div>
      <%= yield %>
    </main>

    <%= render "layouts/footer"%>

    </div>
  </body>
</html>